# Melange
# Author: Dimitris Dimitropoulos <dimitris.dimitropoulos00@gmail.com>
# Author's github: <https://github.com/DimitrisDimitropoulos>
# This theme is a port of the "melange-nvim" colorscheme https://github.com/savq/melange-nvim

"ui.background" = { bg = "a_bg" }
"ui.window" = { fg = "a_fg" }
"ui.text" = { fg = "text_black" }
"ui.text.focus" = { fg = "c_yellow" }

"ui.cursor" = { bg = "b_blue", modifiers = ["reverse"] }
"ui.cursor.primary" ={ bg = "b_blue"}
"ui.cursor.select"={bg="b_magenta"}
"ui.virtual.jump-label"={bg="b_green_dark"}



"ui.selection" = { bg= "b_red" }
"ui.selection.primary" = { bg = "b_yellow"}
"ui.cursorline.primary" = { bg = "b_blue" }
"ui.linenr" = { fg = "a_fg" }
"ui.linenr.selected" = { fg = "b_red", modifiers = ["bold"] }
"ui.virtual.whitespace" = { fg = "a_com" }
"ui.virtual.indent-guide" = { fg = "b_blue" }
"ui.statusline" = { fg = "line_fg", bg = "line_bg" }
"ui.statusline.normal" = { bg = "b_blue", fg = "a_bg", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "b_green", fg = "a_bg", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "b_magenta", fg = "a_bg", modifiers = ["bold"] }
"ui.help" = { bg = "a_bg" }
"ui.menu" = { bg = "a_bg_float" }
"ui.menu.selected" = { bg = "a_ui", fg="b_yellow"}
"ui.menu.scroll" = { fg = "a_bg_float" }
"ui.popup" = { bg = "bg_red" }
"ui.popup.info" = { bg = "a_bg_float" }
"ui.virtual.inlay-hint" = { fg = "a_fg" }
"warning" = { fg = "b_yellow" }
"error" = { fg = "b_red" }
"info" = { fg = "b_blue" }
"hint" = { fg = "b_green" }
"diagnostic" = { modifiers = ["underlined"] }
"diagnostic.error" = { fg = "b_red", underline = { style = "curl", color = "b_red" } }
"diagnostic.warning" = { fg = "b_yellow", underline = { style = "curl", color = "b_yellow" } }
"diagnostic.info" = { fg = "b_blue", underline = { style = "curl", color = "b_blue" } }
"diagnostic.hint" = { fg = "b_green", underline = { style = "curl", color = "b_green" } }
"attribute"={ fg="b_green_dark"}
"tag" = { fg = "text_brown" }
"number" = { fg = "c_magenta" }
"constructor" = { fg = "b_magenta" }
"operator" = { fg = "b_red" }
"string" = { fg = "text_black" }
"string.documentation" = { fg = "b_blue" }
"string.escape" = { fg = "c_blue" }
"string.regexp" = { fg = "b_yellow" }
"string.special" = { fg = "b_red" }
"string.special.symbol" = { fg = "b_red", modifiers = ["italic"] }
"string.special.path" = { fg = "c_blue" }
"string.special.url" = { fg = "c_blue" }
"keyword" = { fg = "b_green_dark" }
"keyword.directive" = { fg = "b_green" }
"keyword.function" = { fg = "b_red" }
"keyword.import" = { fg = "b_yellow" }
"constant" = { fg = "b_blue" }
"constant.builtin" = { fg = "c_magenta" }
"constant.macro" = { fg = "d_green" }
"module" = { fg = "b_red" }
"module.builtin" = { fg = "b_blue" }
"label" = { fg = "b_cyan" }

"variable" = { fg = "d_blue" }

"variable.parameter" = { fg = "b_red" }
"variable.builtin" = { fg = "b_red", modifiers = ["italic"] }
"type" = { fg = "b_blue" }
"type.qualifier" = { fg = "c_yellow" }
"function.macro" = { fg = "b_yellow" }
"function.call" = { fg = "d_yellow" }
"punctuation.delimiter" = { fg = "c_red" }
"punctuation" = { fg = "d_yellow" }
"comment" = { fg = "a_com", modifiers = ["italic"] }
"comment.documentation" = { fg = "a_com" }
"comment.todo" = { fg = "a_com", modifiers = ["bold"] }
"comment.error" = { fg = "a_com", modifiers = ["bold"] }
"comment.warning" = { fg = "a_com", modifiers = ["bold"] }
"comment.note" = { fg = "a_com", modifiers = ["bold"] }

"markup" ={ bg="b_magenta"}
"markup.heading" = { fg = "c_yellow" }
"markup.heading.2" = { fg = "b_yellow" }
"markup.heading.3" = { fg = "b_green" }
"markup.heading.4" = { fg = "b_cyan" }
"markup.italic" = { modifiers = ["italic"] }
"markup.strong" = { modifiers = ["bold"] }
"markup.underline" = { modifiers = ["underlined"] }
"markup.quote" = { fg = "a_com", modifiers = ["italic"] }
"markup.link" = { modifiers = ["underline"] }
"markup.link.url" = { fg = "c_blue" }
"markup.raw" = { fg = "a_com" }
"markup.list" = { fg = "d_yellow" }
"diff.plus" = { bg = "d_green" }
"diff.minus" = { bg = "d_red" }
"diff.delta" = { bg = "d_magenta" }
"diff.delta.moved" = { fg = "d_blue" }
"tag.attribute" = { fg = "b_cyan" }
"tag.delimiter" = { fg = "d_yellow" }


[palette]
# normal 
text_black="#54433A"
text_brown="#A98A78"
# basic
a_fg = "#C4B1A5"
a_fg_dark="#d9d7d7"
a_bg = "#F1F1F1"
a_bg_float = "#faf7f5"
a_float = "#34302C"


# grays
a_sel = "#403A36"
a_ui = "#867462"
a_com = "#C1A78E"
# bright foreground colors
b_red = "#D47766"
b_yellow = "#EBC06D"
b_green = "#87A190"
b_cyan = "#89B3B6"
b_blue = "#A3A9CE"
b_magenta = "#CF9BC2"
# dark color variation 
b_green_dark="#3D6568"
# foreground colors
c_red = "#BD8183"
c_yellow = "#E49B5D"
c_green = "#78997A"
c_cyan = "#7B9695"
c_blue = "#7F91B2"
c_magenta = "#826480"

# backround colors
d_red = "#7D2A2F"
d_yellow = "#8B7449"
d_green = "#233524"
d_cyan = "#253333"
d_blue = "#273142"
d_magenta = "#735e71"

# ui color
line_fg = "#88C0D0"
line_bg = "#4C566A"
